### Cross Validation:
- cross validation is mainly used to check how well the model performing on the unseen data(test data)
- To access the model towards genaralization,we have to build different models , during this process the model learns from test data leads to data leakage,not allowed.To address this we use cross validation.
- In cross validation we divide the training data into train and validation sets and comparing the mean train value and mean validation value if they are similar than the model os genaralized
- There are different types of Cross validations are available:
  1. k-Fold Cross-Validation
    - Data is divided into **k equal folds**
    - Model trains on **k-1 folds** and tests on the remaining fold
    - Process repeats **k times**, each fold used once as test set
    - Final score = **average of all k results**
    - Most commonly used CV method

  2. Stratified k-Fold CV
    - Same as k-fold, but **class distribution is preserved** in each fold
    - Very useful for **classification problems with imbalanced data**

  3. Leave-One-Out Cross-Validation (LOOCV)
    - Special case of k-fold where **k = number of samples**
    - Each time, **1 sample = test set**, rest = training
    - Very accurate but **computationally expensive**

  4. Leave-P-Out Cross-Validation (LPOCV)
    - Similar to LOOCV, but **P samples** are used as test set each time
    - Even more computationally costly than LOOCV

  5. Repeated k-Fold CV
    - k-Fold CV repeated **multiple times with different random splits**
    - Produces **more stable performance estimates**


In [29]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold

In [2]:
from sklearn.datasets import load_breast_cancer

In [3]:
data = load_breast_cancer()
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [4]:
X= data.data
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [5]:
y = data.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [6]:
data.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [8]:
df = pd.DataFrame(X,columns=data.feature_names)
df['target'] = y
df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0


In [9]:
df.shape

(569, 31)

In [10]:
#No need of eda
# Assumption: all the features are having dependency with target.It is possible to predict the target from features
X = df.drop('target',axis=1)
y = df['target']
X.shape,y.shape

((569, 30), (569,))

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=15,stratify=y)
X_train.shape,X_test.shape,y_train.shape,y_test.shape
# change the random state to check for variance

((455, 30), (114, 30), (455,), (114,))

In [21]:
#Assumption no feature needs preprocessing

In [29]:
# simple and complex models - access the  bias and variance
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [23]:
simple_knn = KNeighborsClassifier(n_neighbors=X_train.shape[0])
simple_knn

KNeighborsClassifier(n_neighbors=455)

In [28]:
simple_knn.fit(X_train,y_train)
simple_knn.score(X_train,y_train)

0.6263736263736264

In [30]:
y_pred = simple_knn.predict(X_test)
accuracy_score(y_pred,y_test)

0.631578947368421

In [51]:
complex_knn = KNeighborsClassifier(n_neighbors=1)
complex_knn

KNeighborsClassifier(n_neighbors=1)

In [52]:
complex_knn.fit(X_train,y_train)
complex_knn.score(X_train,y_train)

1.0

In [53]:
y_pred = complex_knn.predict(X_test)
accuracy_score(y_pred,y_test) # large scope for learning,high variance,bias low [Overfitting]

0.956140350877193

In [36]:
simple_dt = DecisionTreeClassifier(max_depth=2)
simple_dt

DecisionTreeClassifier(max_depth=2)

In [37]:
simple_dt.fit(X_train,y_train)
simple_dt.score(X_train,y_train)

0.9582417582417583

In [38]:
y_pred = simple_dt.predict(X_test)
accuracy_score(y_pred,y_test)

0.9473684210526315

In [54]:
complex_Dt = DecisionTreeClassifier()
complex_Dt

DecisionTreeClassifier()

In [67]:
complex_Dt.fit(X_train,y_train)
complex_Dt.score(X_train,y_train)

1.0

In [68]:
y_pred = complex_Dt.predict(X_test)
accuracy_score(y_pred,y_test)

0.9649122807017544

- If the model is complex tends to `Overfitting`
- If the model is simple tends to `Underfitting`

## Cross validation:Detect the genaralization

In [85]:
from sklearn.model_selection import KFold,RepeatedKFold

In [70]:
kf = KFold(n_splits=5,shuffle=True)
kf

KFold(n_splits=5, random_state=None, shuffle=True)

In [72]:
knn = KNeighborsClassifier()

In [71]:
from sklearn.model_selection import cross_validate,cross_val_score

In [74]:
score = cross_validate(knn,X_train,y_train,scoring='accuracy',cv=kf,return_train_score=True)
score

{'fit_time': array([0.00834274, 0.00730824, 0.00803447, 0.        , 0.        ]),
 'score_time': array([0.04067779, 0.02843022, 0.04079795, 0.02815723, 0.0418396 ]),
 'test_score': array([0.94505495, 0.96703297, 0.92307692, 0.85714286, 0.91208791]),
 'train_score': array([0.93681319, 0.93406593, 0.94230769, 0.96153846, 0.93681319])}

In [77]:
score['train_score'].mean()

0.9423076923076923

In [78]:
score['test_score'].mean()

0.9208791208791208

In [79]:
score['test_score'].var(ddof = 0) #variance is low

0.0013718149981886258

In [81]:
# used only to evaluate validation score
score = cross_val_score(knn,X_train,y_train,scoring='accuracy',cv=kf)
score

array([0.95604396, 0.93406593, 0.96703297, 0.86813187, 0.91208791])

In [82]:
score.mean()

0.9274725274725275

In [83]:
score.var(ddof = 0)

0.001236565632170028

- repeated kfold cv

In [86]:
from sklearn.model_selection import RepeatedKFold

In [90]:
rkf = RepeatedKFold(n_splits=5,n_repeats=10)
rkf

RepeatedKFold(n_repeats=10, n_splits=5, random_state=None)

In [91]:
score = cross_validate(knn,X_train,y_train,scoring='accuracy',cv=rkf,return_train_score=True)
score

{'fit_time': array([0.00319839, 0.01073384, 0.00308299, 0.00609732, 0.        ,
        0.        , 0.00588441, 0.00232577, 0.00888705, 0.00456309,
        0.        , 0.01566029, 0.00715089, 0.01073527, 0.00820708,
        0.        , 0.01627326, 0.        , 0.        , 0.        ,
        0.00402689, 0.00402737, 0.00835872, 0.01360512, 0.01148725,
        0.0080812 , 0.01609063, 0.01615906, 0.00578833, 0.0045867 ,
        0.01171088, 0.        , 0.00708365, 0.        , 0.        ,
        0.01324534, 0.        , 0.        , 0.00747705, 0.00553679,
        0.        , 0.00402617, 0.00931692, 0.01305437, 0.00959945,
        0.0045836 , 0.        , 0.00608253, 0.00817323, 0.        ]),
 'score_time': array([0.03846741, 0.03780246, 0.02860785, 0.02961469, 0.0299809 ,
        0.03818536, 0.03543186, 0.03401494, 0.03389812, 0.0293541 ,
        0.04289293, 0.0332973 , 0.03073406, 0.02355504, 0.03234553,
        0.02610135, 0.03241086, 0.03990936, 0.03683519, 0.03207088,
        0.02802873, 

In [92]:
score['train_score'].mean()

0.9422527472527471

In [93]:
score['test_score'].mean()

0.9263736263736264

In [94]:
# used only to evaluate validation score
score = cross_val_score(knn,X_train,y_train,scoring='accuracy',cv=rkf)
score

array([0.91208791, 0.91208791, 0.93406593, 0.92307692, 0.93406593,
       0.92307692, 0.92307692, 0.93406593, 0.91208791, 0.93406593,
       0.92307692, 0.95604396, 0.92307692, 0.94505495, 0.9010989 ,
       0.93406593, 0.95604396, 0.94505495, 0.84615385, 0.92307692,
       0.89010989, 0.93406593, 0.95604396, 0.93406593, 0.91208791,
       0.87912088, 0.92307692, 0.94505495, 0.96703297, 0.93406593,
       0.94505495, 0.9010989 , 0.96703297, 0.93406593, 0.92307692,
       0.87912088, 0.94505495, 0.93406593, 0.96703297, 0.9010989 ,
       0.95604396, 0.91208791, 0.92307692, 0.92307692, 0.91208791,
       0.86813187, 0.89010989, 0.93406593, 0.97802198, 0.96703297])

In [95]:
score.mean()

0.9265934065934066

In [96]:
score.var(ddof=0)

0.0007073541842772614

- stratified cv

In [98]:
from sklearn.model_selection import StratifiedKFold

In [99]:
skf = StratifiedKFold(n_splits=10,shuffle=True,random_state=None)
skf

StratifiedKFold(n_splits=10, random_state=None, shuffle=True)

In [100]:
score = cross_validate(knn,X_train,y_train,scoring='accuracy',cv=skf,return_train_score=True)
score

{'fit_time': array([0.00806832, 0.0079658 , 0.        , 0.00703526, 0.00909638,
        0.00809622, 0.00863886, 0.00459695, 0.0102365 , 0.00725532]),
 'score_time': array([0.02507949, 0.02267313, 0.01615167, 0.01839709, 0.02286553,
        0.02062821, 0.0219233 , 0.01806307, 0.02215481, 0.02133965]),
 'test_score': array([0.93478261, 0.95652174, 0.91304348, 0.91304348, 0.97826087,
        0.95555556, 0.88888889, 0.93333333, 0.95555556, 0.88888889]),
 'train_score': array([0.94376528, 0.93887531, 0.94621027, 0.94865526, 0.93887531,
        0.94146341, 0.94634146, 0.93658537, 0.94146341, 0.95121951])}

In [101]:
score['train_score'].mean()

0.9433454588824617

In [102]:
score['test_score'].mean()

0.9317874396135266

In [103]:
# used only to evaluate validation score
score = cross_val_score(knn,X_train,y_train,scoring='accuracy',cv=skf)
score

array([0.95652174, 0.89130435, 0.89130435, 0.95652174, 0.97826087,
       0.91111111, 0.93333333, 0.88888889, 0.93333333, 0.97777778])

In [104]:
score.mean()

0.9318357487922706

In [105]:
score.var(ddof=0)

0.0011048775934094156

- Leave one out cv

In [106]:
from sklearn.model_selection import LeaveOneOut

In [108]:
# 454 data points are considered for training and one for validation
loocv = LeaveOneOut()
loocv

LeaveOneOut()

In [109]:
score = cross_validate(knn,X_train,y_train,scoring='accuracy',cv=loocv,return_train_score=True)
score

{'fit_time': array([0.00756836, 0.00710154, 0.01602769, 0.00503325, 0.01467419,
        0.00378895, 0.        , 0.00604534, 0.01461411, 0.0103991 ,
        0.00150347, 0.00649786, 0.00498629, 0.00795794, 0.        ,
        0.        , 0.00257468, 0.        , 0.        , 0.00574589,
        0.        , 0.00958991, 0.        , 0.01680636, 0.00810528,
        0.        , 0.        , 0.00605106, 0.01109171, 0.00341797,
        0.00973988, 0.01267219, 0.00259519, 0.00473738, 0.00736785,
        0.00891829, 0.        , 0.00808716, 0.0098772 , 0.01119494,
        0.        , 0.        , 0.        , 0.01214409, 0.00730228,
        0.01427197, 0.00645804, 0.00509405, 0.        , 0.00359893,
        0.        , 0.        , 0.01453567, 0.00811434, 0.01006722,
        0.01210237, 0.        , 0.00401282, 0.        , 0.        ,
        0.00433874, 0.00895572, 0.0052352 , 0.01384783, 0.00307107,
        0.00951314, 0.0080936 , 0.        , 0.00807333, 0.00404572,
        0.00907874, 0.00782394, 0.  

In [110]:
score['train_score'].mean()

0.9450162172629134

In [111]:
score['test_score'].mean()

0.9296703296703297

In [113]:
# used only to evaluate validation score
score = cross_val_score(knn,X_train,y_train,scoring='accuracy',cv=loocv)
score

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1.,
       1., 1., 1., 1., 1.

In [114]:
score.mean()

0.9296703296703297

In [115]:
score.var(ddof = 0) #var high due to only one data point for testing

0.06538340780099022

- Leavepout

In [116]:
from sklearn.model_selection import LeavePOut

In [117]:
lpocv = LeavePOut(p = 5)
lpocv

LeavePOut(p=5)

In [121]:
score = cross_validate(knn,X_train.iloc[:10],y_train[:10],scoring='accuracy',cv=lpocv,return_train_score=True)
score

{'fit_time': array([0.01147532, 0.00672174, 0.00404382, 0.00445604, 0.0039413 ,
        0.00136781, 0.        , 0.        , 0.00508809, 0.00418258,
        0.00201488, 0.00402451, 0.00328612, 0.00402141, 0.00550485,
        0.00554276, 0.00151134, 0.        , 0.00252795, 0.00402856,
        0.        , 0.00304389, 0.00205898, 0.00409341, 0.00217843,
        0.00402665, 0.00725889, 0.01133108, 0.01283574, 0.0170269 ,
        0.00785112, 0.01088023, 0.00604653, 0.00811815, 0.00709248,
        0.00816226, 0.01192331, 0.01214504, 0.01426983, 0.01522231,
        0.00662208, 0.00590801, 0.01041317, 0.00794387, 0.00983286,
        0.00984097, 0.00808644, 0.00781584, 0.00851607, 0.00609803,
        0.        , 0.00849104, 0.00534177, 0.        , 0.00888634,
        0.        , 0.00669646, 0.00809193, 0.        , 0.01942682,
        0.00820231, 0.        , 0.01387787, 0.00362921, 0.        ,
        0.00967312, 0.00247908, 0.00708008, 0.00841165, 0.        ,
        0.        , 0.        , 0.00

In [122]:
score['train_score'].mean()

0.6428571428571429

In [123]:
score['test_score'].mean()

0.35714285714285715

---