### Evaluation metrics:
- Evaluation metrics are used to measure how well our machine learning model performs on unseen data
- These are mainly separated into two types based on type of target
#### Classification metrics:
1. **Accuracy:**
   - The percentage of total predictions that are correct
2. **Precision:**
   - Out of all predictive positives , how many were actually positively predicted
3. **Recall:**
   - Out of all actual positives, how many were correctly predicted
4. **Confusion matrix:**
   - It is the table that shows TP,TN,FP,FN to understand the prediction type
5. **F1 score:**
    - It it Harmonic mean of precision and recall
#### Regression metrics:
1. **MAE (Mean Absolute Error):**  
  - Average absolute difference between actual and predicted values.

2. **MSE (Mean Squared Error):**  
  - Average of squared errors

3. **RMSE (Root Mean Squared Error):**  
  - Square root of MSE, interpretable in the same units as the target.

4. **R² Score (Coefficient of Determination):**  
  - Measures how much variance in the target is explained by the model.

5. **Adjusted R²:**  
  - Modified R² that penalizes adding unnecessary features.

6. **MAPE (Mean Absolute Percentage Error):**  
  Average percentage error; useful when scale matters.



## Classification Metrics

In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,confusion_matrix

In [4]:
y = np.array([0,1,0,1,0,1,0,1,0,1,0])
y

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [5]:
y_pred = np.array([0,0,0,0,0,0,1,1,1,1,1])
y_pred

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [7]:
confusion_matrix(y,y_pred)

array([[3, 3],
       [3, 2]], dtype=int64)

In [8]:
accuracy_score(y,y_pred)

0.45454545454545453

In [9]:
5/11 #Manual implementation

0.45454545454545453

In [10]:
precision_score(y,y_pred)

0.4

In [11]:
2/5

0.4

In [12]:
recall_score(y,y_pred)

0.4

In [13]:
2/5

0.4

In [14]:
f1_score(y,y_pred)

0.4

In [15]:
2/5

0.4

In [39]:
# class with imbalence data
y_act = np.array([0,0,0,0,0,0,0,0,0,0,0,1,1,1])
y_act

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1])

In [46]:
y_pred = np.array([0,0,0,0,0,0,0,0,0,1,0,0,0,1])
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1])

In [47]:
confusion_matrix(y_act,y_pred)

array([[10,  1],
       [ 2,  1]], dtype=int64)

In [48]:
accuracy_score(y_act,y_pred)

0.7857142857142857

In [49]:
precision_score(y_act,y_pred)

0.5

In [50]:
recall_score(y_act,y_pred)

0.3333333333333333

In [51]:
f1_score(y_act,y_pred)

0.4

In [52]:
from sklearn.metrics import balanced_accuracy_score

In [54]:
balanced_accuracy_score(y_act,y_pred)

0.6212121212121212

In [55]:
from sklearn.metrics import fbeta_score

In [56]:
#Imbal data - correct classification on minority class
# correct classification of true positives
# more importance to recall  - recall is twice important as precision
#beta-2
fbeta_score(y_act,y_pred,beta=2)

0.35714285714285715

In [57]:
fbeta_score(y_act,y_pred,beta=0.5)

0.45454545454545453

In [58]:
fbeta_score(y_act,y_pred,beta=1)

0.4